### ISSUE TITLE
Add google analytics

### ISSUE THREAD

**Issue by web3projectlink** [web3projectlinks/web3projectlinks#12]
https://nextjs.org/docs/app/building-your-application/optimizing/third-party-libraries#google-analytics

**Comment by Siddarthan999** [comment]
G-VQJV22LQH8

**Comment by Siddarthan999** [comment]
Limit of 25 user-scoped custom dimensions

**Comment by Ghastly2001** [comment]
I came to work on this enhancement feature but seems like it's already done.

**Comment by web3projectlink** [comment]
https://github.com/web3projectlinks/web3projectlinks/pull/13
